version: “3.8”

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432" # Map host port 5432 to container port 5432
    environment:
      - DATABASE_HOST= 127.0.0.1
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "business88jb@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - "5050:5050" # Map host port 5050 to container port 5050
    depends_on:
      - postgres
