name: test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: unbuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          npm run test
