name: "Unit tests"

on: [pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    setps:
      - uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v2

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
